name: Trigger auto deployment for bplive-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/bplive-app-AutoDeployTrigger-a380b8b1-ceac-4755-989c-dc9352c9b2ff.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.BPLIVEAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: bplive.azurecr.io
          registryUsername: ${{ secrets.BPLIVEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BPLIVEAPP_REGISTRY_PASSWORD }}
          containerAppName: bplive-app
          resourceGroup: Backend
          imageToBuild: bplive.azurecr.io/bplive:${{ github.sha }}
          dockerfilePath: Dockerfile
          targetPort: 8000
          environmentVariables: '
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            BKK_API=${{ secrets.BKK_API }}
            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
            LOGOUT_REDIRECT_URI=${{ secrets.LOGOUT_REDIRECT_URI }}
            LOGIN_REDIRECT_URI=${{ secrets.LOGIN_REDIRECT_URI }}
          '
